@baseUrl = http://localhost:3001
@contentType = application/json

### 1. Get all vehicles
GET {{baseUrl}}/vehicles

### 2. Create a new vehicle
POST {{baseUrl}}/vehicles
Content-Type: {{contentType}}

{
    "marque": "Toyota",
    "model": "Carina",
    "immatriculation": "ABC-5005",
    "annees": 2025,
    "prixLocation": 204000
}



### 5. Get specific vehicle by ID
GET {{baseUrl}}/vehicles/d8e65c39-04d1-45e9-8761-cf328ddfe7be

### 6. Update the vehicle
PUT {{baseUrl}}/vehicles/d8e65c39-04d1-45e9-8761-cf328ddfe7be
Content-Type: {{contentType}}

{
    "model": "corolla",
    "prixLocation": 36000000
}

### 7. Search vehicle by immatriculation
GET {{baseUrl}}/vehicles/search/ABC-5005

### 8. Filter vehicles by max price
GET {{baseUrl}}/vehicles/price/36000000

### 9. Delete the vehicle
DELETE {{baseUrl}}/vehicles/d8e65c39-04d1-45e9-8761-cf328ddfe7be
