@baseUrl = http://localhost:3001
@contentType = application/json
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5NzNhZDc3LTI5NmYtNDZkOS1hNTA2LWRlOTdhNGU2ZjI1NiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjA5NDQwNCwiZXhwIjoxNzQ2MDk1MzA0fQ.KyTvtWETIGfOE1uHeL-FDJab13tSD6QVUgSaitnpYi0
@userToken = votre_token_utilisateur_ici


### 1. Login (pour obtenir le token)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "name": "admin",
    "password": "admin123"
}


### 2. Créer un nouvel utilisateur (Admin seulement)
POST {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
    "name": "kevin",
    "password": "secret1234",
    "role": "user"
}

### 3. Mettre à jour un utilisateur
PUT {{baseUrl}}/users/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}  # Ou userToken si c'est son propre profil

{
    "name": "john_doe_updated",
    "password": "newpassword123"
}


### 4. Rafraîchir le token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5NzNhZDc3LTI5NmYtNDZkOS1hNTA2LWRlOTdhNGU2ZjI1NiIsImlhdCI6MTc0NjA5NDI3OSwiZXhwIjoxNzQ2Njk5MDc5fQ.lZF3_VIQCeu5N5V9C317fYiug7LalGH3Ciwm4QVIEv4"
}

### 5. Obtenir tous les utilisateurs (Admin seulement)
GET {{baseUrl}}/users
Authorization: Bearer {{adminToken}}

### 6. Obtenir un utilisateur spécifique
GET {{baseUrl}}/users/1
Authorization: Bearer {{adminToken}}  # Ou userToken si c'est son propre profil


### 7. Supprimer un utilisateur (Admin seulement)
DELETE {{baseUrl}}/users/44e96eca-66a6-4d6b-873a-19044d48a16d
Authorization: Bearer {{adminToken}}

### 8. Obtenir le profil de l'utilisateur connecté
GET {{baseUrl}}/users/me
Authorization: Bearer {{userToken}}

### 9. Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Authorization: Bearer {{userToken}}

{
    "refreshToken": "votre_refresh_token_ici"
}



