### GET /vehicule
GET http://localhost:3001/vehicules

### POST /vehicule/:id
POST http://localhost:3001/vehicule/:1

### PUT /vehicule/:id
PUT http://localhost:3001/vehicule/:1

### DELETE /vehicule/:id
DELETE http://localhost:3001/vehicule/:1

### GET /vehicule/:id
GET http://localhost:3001/vehicule/:1

### GET /vehicule/search/:immatriculation
GET http://localhost:3001/vehicule/search/:782d

### GET /vehicule/price/:PrixMax
GET http://localhost:3001/vehicule/price/:400000